=== ovidiu-144/FcBarcelonaWeb/continut/resurse/persoane.dtd
<!ELEMENT jucatori (jucator+)>
<!ELEMENT jucator (nume, prenume, varsta, nationalitate, pozitie, numar_tricou, valoare_piata, contract)>
<!ATTLIST jucator id CDATA #REQUIRED>

<!ELEMENT contract (inceput, sfarsit, salariu_saptamanal, clauze)>
<!ELEMENT clauze (clauza+)>

<!ELEMENT nume (#PCDATA)>
<!ELEMENT prenume (#PCDATA)>
<!ELEMENT varsta (#PCDATA)>
<!ELEMENT nationalitate (#PCDATA)>
<!ELEMENT pozitie (#PCDATA)>
<!ELEMENT numar_tricou (#PCDATA)>
<!ELEMENT valoare_piata (#PCDATA)>
<!ELEMENT inceput (#PCDATA)>
<!ELEMENT sfarsit (#PCDATA)>
<!ELEMENT salariu_saptamanal (#PCDATA)>
<!ELEMENT clauza (#PCDATA)>

=== ovidiu-144/FcBarcelonaWeb/continut/resurse/persoane.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE jucatori SYSTEM "persoane.dtd">
<jucatori>

    <!-- ==================== PORTARI ==================== -->

    <jucator id="1">
        <nume> Garcia </nume>
        <prenume> Joan </prenume>
        <varsta> 23 </varsta>
        <nationalitate> Spania </nationalitate>
        <pozitie> Portar </pozitie>
        <numar_tricou> 13 </numar_tricou>
        <valoare_piata> 40mil </valoare_piata>
        <contract>
            <inceput> 2025-07-01 </inceput>
            <sfarsit> 2030-06-30 </sfarsit>
            <salariu_saptamanal> 120k </salariu_saptamanal>
            <clauze>
                <clauza> Clauza de reziliere: 100000000 </clauza>
            </clauze>
        </contract>
    </jucator>

    <jucator id="2">
        <nume> Szczesny </nume>
        <prenume> Wojciech </prenume>
        <varsta> 34 </varsta>
        <nationalitate> Polonia </nationalitate>
        <pozitie> Portar </pozitie>
        <numar_tricou> 25 </numar_tricou>
        <valoare_piata> 900k </valoare_piata>
        <contract>
            <inceput> 2024-10-01 </inceput>
            <sfarsit> 2026-06-30 </sfarsit>
            <salariu_saptamanal> 57k </salariu_saptamanal>
            <clauze>
                <clauza> Contract pe un an cu optiune de prelungire </clauza>
            </clauze>
        </contract>
    </jucator>

    <!-- ==================== FUNDASI ==================== -->

    <jucator id="3">
        <nume> Balde </nume>
        <prenume> Alejandro </prenume>
        <varsta> 21 </varsta>
        <nationalitate> Spania </nationalitate>
        <pozitie> Fundas Stanga </pozitie>
        <numar_tricou> 3 </numar_tricou>
        <valoare_piata> 55mil </valoare_piata>
        <contract>
            <inceput> 2022-07-01 </inceput>
            <sfarsit> 2028-06-30 </sfarsit>
            <salariu_saptamanal> 32k </salariu_saptamanal>
            <clauze>
                <clauza> Clauza de reziliere: 1000000000 </clauza>
            </clauze>
        </contract>
    </jucator>

    <jucator id="4">
        <nume> Araujo </nume>
        <prenume> Ronald </prenume>
        <varsta> 25 </varsta>
        <nationalitate> Uruguay </nationalitate>
        <pozitie> Fundas Central </pozitie>
        <numar_tricou> 4 </numar_tricou>
        <valoare_piata> 20mil </valoare_piata>
        <contract>
            <inceput> 2024-07-01 </inceput>
            <sfarsit> 2031-06-30 </sfarsit>
            <salariu_saptamanal> 240k </salariu_saptamanal>
            <clauze>
                <clauza> Clauza de reziliere: 1000000000 </clauza>
            </clauze>
        </contract>
    </jucator>

    <jucator id="5">
        <nume> Cubarsi </nume>
        <prenume> Pau </prenume>
        <varsta> 18 </varsta>
        <nationalitate> Spania </nationalitate>
        <pozitie> Fundas Central </pozitie>
        <numar_tricou> 5 </numar_tricou>
        <valoare_piata> 80mil </valoare_piata>
        <contract>
            <inceput> 2024-07-01 </inceput>
            <sfarsit> 2029-06-30 </sfarsit>
            <salariu_saptamanal> 76k </salariu_saptamanal>
            <clauze>
                <clauza> Clauza de reziliere: 1000000000 </clauza>
            </clauze>
        </contract>
    </jucator>

    <jucator id="6">
        <nume> Christensen </nume>
        <prenume> Andreas </prenume>
        <varsta> 28 </varsta>
        <nationalitate> Danemarca </nationalitate>
        <pozitie> Fundas Central </pozitie>
        <numar_tricou> 15 </numar_tricou>
        <valoare_piata> 9mil </valoare_piata>
        <contract>
            <inceput> 2022-07-01 </inceput>
            <sfarsit> 2026-06-30 </sfarsit>
            <salariu_saptamanal> 173k </salariu_saptamanal>
            <clauze>
                <clauza> Clauza de reziliere: 400000000 </clauza>
            </clauze>
        </contract>
    </jucator>

    <jucator id="7">
        <nume> Kounde </nume>
        <prenume> Jules </prenume>
        <varsta> 26 </varsta>
        <nationalitate> Franta </nationalitate>
        <pozitie> Fundas Dreapta </pozitie>
        <numar_tricou> 23 </numar_tricou>
        <valoare_piata> 65mil </valoare_piata>
        <contract>
            <inceput> 2022-07-01 </inceput>
            <sfarsit> 2030-06-30 </sfarsit>
            <salariu_saptamanal> 300k </salariu_saptamanal>
            <clauze>
                <clauza> Clauza de reziliere: 1000000000 </clauza>
            </clauze>
        </contract>
    </jucator>

    <jucator id="8">
        <nume> Garcia </nume>
        <prenume> Eric </prenume>
        <varsta> 23 </varsta>
        <nationalitate> Spania </nationalitate>
        <pozitie> Fundas Central </pozitie>
        <numar_tricou> 24 </numar_tricou>
        <valoare_piata> 35mil </valoare_piata>
        <contract>
            <inceput> 2021-07-01 </inceput>
            <sfarsit> 2026-06-30 </sfarsit>
            <salariu_saptamanal> 150k </salariu_saptamanal>
            <clauze>
                <clauza> Clauza de reziliere: 400000000 </clauza>
            </clauze>
        </contract>
    </jucator>

    <jucator id="9">
        <nume> Martin </nume>
        <prenume> Gerard </prenume>
        <varsta> 22 </varsta>
        <nationalitate> Spania </nationalitate>
        <pozitie> Fundas Stanga </pozitie>
        <numar_tricou> 18 </numar_tricou>
        <valoare_piata> 25mil </valoare_piata>
        <contract>
            <inceput> 2024-07-01 </inceput>
            <sfarsit> 2028-06-30 </sfarsit>
            <salariu_saptamanal> 30k </salariu_saptamanal>
            <clauze>
                <clauza> Clauza de reziliere: 100000000 </clauza>
            </clauze>
        </contract>
    </jucator>

    <jucator id="10">
        <nume> Joao </nume>
        <prenume> Cancelo </prenume>
        <varsta> 31 </varsta>
        <nationalitate> Portugalia </nationalitate>
        <pozitie> Fundas Stanga </pozitie>
        <numar_tricou> 2 </numar_tricou>
        <valoare_piata> 9mil </valoare_piata>
        <contract>
            <inceput> 2026-01-13 </inceput>
            <sfarsit> 2026-06-30 </sfarsit>
            <salariu_saptamanal> 160k </salariu_saptamanal>
            <clauze>
                <clauza> Imprumutat de la AL Hilal </clauza>
            </clauze>
        </contract>
    </jucator>

    <!-- ==================== MIJLOCASI ==================== -->

    <jucator id="10">
        <nume> Gavi </nume>
        <prenume> Pablo </prenume>
        <varsta> 20 </varsta>
        <nationalitate> Spania </nationalitate>
        <pozitie> Mijlocas </pozitie>
        <numar_tricou> 6 </numar_tricou>
        <valoare_piata> 30mil </valoare_piata>
        <contract>
            <inceput> 2022-07-01 </inceput>
            <sfarsit> 2030-06-30 </sfarsit>
            <salariu_saptamanal> 180k </salariu_saptamanal>
            <clauze>
                <clauza> Clauza de reziliere: 1000000000 </clauza>
            </clauze>
        </contract>
    </jucator>

    <jucator id="11">
        <nume> Pedri </nume>
        <prenume> Pedro </prenume>
        <varsta> 23 </varsta>
        <nationalitate> Spania </nationalitate>
        <pozitie> Mijlocas </pozitie>
        <numar_tricou> 8 </numar_tricou>
        <valoare_piata> 150mil </valoare_piata>
        <contract>
            <inceput> 2023-07-01 </inceput>
            <sfarsit> 2030-06-30 </sfarsit>
            <salariu_saptamanal> 240k </salariu_saptamanal>
            <clauze>
                <clauza> Clauza de reziliere: 1000000000 </clauza>
            </clauze>
        </contract>
    </jucator>

    <jucator id="12">
        <nume> de Jong </nume>
        <prenume> Frenkie </prenume>
        <varsta> 27 </varsta>
        <nationalitate> Olanda </nationalitate>
        <pozitie> Mijlocas </pozitie>
        <numar_tricou> 21 </numar_tricou>
        <valoare_piata> 45mil </valoare_piata>
        <contract>
            <inceput> 2019-07-01 </inceput>
            <sfarsit> 2026-06-30 </sfarsit>
            <salariu_saptamanal> 365k </salariu_saptamanal>
            <clauze>
                <clauza> Clauza de reziliere: 400000000 </clauza>
            </clauze>
        </contract>
    </jucator>

    <jucator id="13">
        <nume> Casado </nume>
        <prenume> Marc </prenume>
        <varsta> 21 </varsta>
        <nationalitate> Spania </nationalitate>
        <pozitie> Mijlocas Defensiv </pozitie>
        <numar_tricou> 17 </numar_tricou>
        <valoare_piata> 20mil </valoare_piata>
        <contract>
            <inceput> 2024-07-01 </inceput>
            <sfarsit> 2028-06-30 </sfarsit>
            <salariu_saptamanal> 24k </salariu_saptamanal>
            <clauze>
                <clauza> Clauza de reziliere: 100000000 </clauza>
            </clauze>
        </contract>
    </jucator>

    <jucator id="14">
        <nume> Bernal </nume>
        <prenume> Marc </prenume>
        <varsta> 18 </varsta>
        <nationalitate> Spania </nationalitate>
        <pozitie> Mijlocas </pozitie>
        <numar_tricou> 22 </numar_tricou>
        <valoare_piata> 30mil </valoare_piata>
        <contract>
            <inceput> 2024-07-01 </inceput>
            <sfarsit> 2026-06-30 </sfarsit>
            <salariu_saptamanal> 24k </salariu_saptamanal>
            <clauze>
                <clauza> Optiune de prelungire pana in 2029 </clauza>
            </clauze>
        </contract>
    </jucator>

    <jucator id="15">
        <nume> Olmo </nume>
        <prenume> Dani </prenume>
        <varsta> 26 </varsta>
        <nationalitate> Spania </nationalitate>
        <pozitie> Mijlocas Ofensiv </pozitie>
        <numar_tricou> 20 </numar_tricou>
        <valoare_piata> 60mil </valoare_piata>
        <contract>
            <inceput> 2024-07-01 </inceput>
            <sfarsit> 2030-06-30 </sfarsit>
            <salariu_saptamanal> 240k </salariu_saptamanal>
            <clauze>
                <clauza> Clauza de reziliere: 1000000000 </clauza>
            </clauze>
